import type { ResolvedConfig, FeatureFlags, FeatureState } from './types';

export const DEFAULT_FEATURE_FLAGS: FeatureFlags = {
  profiles: true,
  biggerText: true,
  textSpacing: true,
  lineHeight: true,
  contrast: true,
  smartContrast: true,
  highlightLinks: true,
  pauseAnimations: true,
  hideImages: true,
  dyslexiaFont: true,
  legibleFont: true,
  bigCursor: true,
  readingGuide: true,
  readingMask: true,
  tooltips: true,
  pageStructure: true,
  textAlign: true,
  saturation: true,
  readAloud: true,
  semanticAssist: false,
};

export const DEFAULT_FEATURE_STATE: FeatureState = {
  profile: null,
  biggerText: 0,
  textSpacing: 0,
  lineHeight: 0,
  contrast: 'off',
  smartContrast: false,
  highlightLinks: false,
  pauseAnimations: false,
  hideImages: false,
  dyslexiaFont: false,
  legibleFont: false,
  bigCursor: false,
  readingGuide: false,
  readingMask: false,
  tooltips: false,
  pageStructure: false,
  textAlign: 'off',
  saturation: 'off',
  readAloud: false,
  semanticAssist: false,
};

export const DEFAULT_CONFIG: ResolvedConfig = {
  enabled: true,
  autoInit: true,
  position: 'right',
  offsetY: '50%',
  zIndex: 999999,
  size: 'regular',
  language: 'auto',
  storage: 'local',
  persist: true,
  safeMode: true,
  cspNonce: null,
  launcherIcon: 'default',
  theme: 'system',
  features: { ...DEFAULT_FEATURE_FLAGS },
  defaults: { ...DEFAULT_FEATURE_STATE },
  profiles: {},
  selectors: {
    scope: [],
    exclude: [],
  },
};
